image:
  repository: harbor.patras5g.eu/5gasp_private/neo-main-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: 5gaspsecret

redis:
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: false

mongodb:
  fullnameOverride: mongo
  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: false
