apiVersion: v1
kind: Service
metadata:
  name: neo-transport-api
spec:
  type: NodePort
  selector:
    app: neo-transport-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31391
