apiVersion: v1
kind: Service
metadata:
  name: main-api
spec:
  type: NodePort
  selector:
    app: main-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31390
