apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-routing-engine-estimation
spec:
  selector:
    matchLabels:
      app: neo-routing-engine-estimation
  replicas: 1
  template:
    metadata:
      labels:
        app: neo-routing-engine-estimation
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: neo-routing-engine-estimation
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_URI
          value: "mongodb://mongo"
        - name: OSRM_API_ENDPOINT
          value: "http://osrm"
