apiVersion: v1
kind: Service
metadata:
  name: neo-routing-engine
spec:
  type: NodePort
  selector:
    app: neo-routing-engine
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31392
