apiVersion: v1
name: osrm
description: OSRM - Open Source Routing Machine
version: 1.1.0
appVersion: "5.22.0"
keywords:
  - osrm
sources:
- https://github.com/Project-OSRM/osrm-backend
kubeVersion: ">= 1.19.0-0"
